name: Cross-Platform Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install pyinstaller cryptography

      # WINDOWS
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: pyinstaller --noconsole --onefile --icon="${{ github.workspace }}/icon.ico" --name "FileEncrypter_Win" main.py

      # MAC
      - name: Build Mac
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --noconsole --onefile --windowed --icon="${{ github.workspace }}/icon.icns" --name "FileEncrypter_Mac" main.py
          cd dist && zip -r ../FileEncrypter_Mac.zip FileEncrypter_Mac.app

      # LINUX
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: pyinstaller --noconsole --onefile --name "FileEncrypter_Linux" main.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            dist/FileEncrypter_Win.exe
            dist/FileEncrypter_Linux
            FileEncrypter_Mac.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: assets
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            assets/**/FileEncrypter_Win.exe
            assets/**/FileEncrypter_Mac.zip
            assets/**/FileEncrypter_Linux
