      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            # Added --icon="icon.ico" here for Windows
            pyinstaller --noconsole --onefile --icon="icon.ico" --name "FileEncrypter_Win" main.py
          else
            # Mac icon is already here
            pyinstaller --noconsole --onefile --windowed --icon="icon.icns" --name "FileEncrypter_Mac" main.py
          fi
